apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "node-problem-detector.fullname" . }}
  labels:
    {{- include "node-problem-detector.labels" . | nindent 4 }}
data:
  {{- .Values.config | toYaml | nindent 2 }}
